name: coastcast
version: "1.0.0"
config-version: 2
profile: coastcast
model-paths: ["models"]
test-paths: ["tests"]
vars:
  study_start: "2017-01-01T00:00:00Z"
  study_end_exclusive: "2026-01-01T00:00:00Z"
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  coastcast:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
